name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia à meia-noite (UTC)
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js (required by snk)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Generate snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: "yngskkj"
          output_file: "dist/github-contribution-grid-snake.svg"
          # se quiser parâmetros extras, consulte a action Platane/snk

      - name: Generate dark snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: "yngskkj"
          output_file: "dist/github-contribution-grid-snake-dark.svg"
          palette: "github-dark"

      - name: Commit and push to output branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update snake contribution grid"
          file_pattern: "dist/**"
          branch: output
          # usa o GITHUB_TOKEN interno para push
